/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    EditCategoryDialog: typeof import('./src/composables/EditCategoryDialog.vue')['default']
    EditGoalDialog: typeof import('./src/composables/EditGoalDialog.vue')['default']
    EditGoalListDialog: typeof import('./src/composables/EditGoalListDialog.vue')['default']
    EditorComponent: typeof import('./src/components/EditorComponent.vue')['default']
    GameEditorDialog: typeof import('./src/composables/GameEditorDialog.vue')['default']
    GameListDialog__UNUSED_NEEDS_EDITS: typeof import('./src/composables/GameListDialog__UNUSED_NEEDS_EDITS.vue')['default']
    GeneratorComponent: typeof import('./src/components/GeneratorComponent.vue')['default']
    MarkdownRenderer: typeof import('./src/composables/MarkdownRenderer.vue')['default']
    NavbarComponent: typeof import('./src/components/NavbarComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarComponent: typeof import('./src/components/SidebarComponent.vue')['default']
  }
}
